help :-
    write('Available commands:'), nl,
    write(' start         - start the game, show game title and instruction'), nl,
    write(' help          - show all commands and legends'), nl,
    write(' quit          - quit the game'), nl,
    write(' w, a, s, d    - move'), nl,
    write(' map           - show map'), nl,
    write(' heal          - heal all tokemon in inventory, only possible while in gym center'), nl,
    write(' status        - show status of tokemon in inventory and remaining legendary tokemon'), nl,
    write(' pick          - choose tokemon for battle (only usable in battle)'), nl,
    write(' attack        - use normal attack (only usable in battle)'), nl,
    write(' specialAttack - use special attack (only usable in battle)'), nl,
    write(' run           - escape from battle'), nl,
    write(' drop          - remove tokemon from inventory'), nl,
    write(' saveGame(Filename)- save the game'), nl,
    write(' loadGame(Filename)- load the game'), nl,
    write('Legends :'), nl,
    write(' X - Wall'), nl,
    write(' P - Player'), nl,
    write(' G - Gym'), nl,
    write(' L - Legendary Tokemon'), nl,
    write(' T - Normal Tokemon (Only Available in God Mode)'), nl.

